<a href="https://colab.research.google.com/github/Jeromy0515/Jeromy0515/blob/main/random_forest/random_forest5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 시작하기 전에
1. 지금까지 공부: k-최근접 이웃, 선형 회귀, 릿지, 라쏘, 다향 회귀, 로지스틱 회귀, 확률적 경사 하강법, 분류기, 결정트리 모델, 교차 검증, 하이퍼파라미터 튜닝
2. 베스트 머신러닝 알고리즘은 무엇? 결정 트리를 확장하여 머신러닝 계를 제패한 알고리즘은?
3. 결정 트리? 나무 말고 숲을 봐라!
4. 머신러닝, 나무, 숲 -> 랜덤 포레스트(Random Forest)
5. 보편적으로 성능이 좋아 널리 사용되는 알고리즘이 있지만, 문제마다 다를 수 있음 -> 어떤 알고리즘이 더 뛰어나다고 미리 판단하지 말고, 다 테스트해볼 필요가 있음!


# 정형 데이터
- 생선의 길이, 높이, 무게, 대각선 / 와인 데이터 등을 데이터로 사용
- csv 파일에 가지런히 정리되어 있었음
- 행/열이 명확
- structured data
- csv, DB, Excel 등에 저장하기 용이

# 비정형 데이터
- 데이터베이스나 엑셀처럼 행/열로 표현하기 어려운 데이터
- 글과 같은 텍스트 데이터, 디카로 찍은 사진, 디지털 음악 등
- NoSQL은 엑셀이나 csv에 담기 어려운 텍스트, 이미지, 음악 or JSON 데이터 저장

# 정형 / 비정형 데이터
- 지금까지 배운 머신러닝 알고리즘은 정형 데이터에 잘 맞음
- 그 중에서도 가장 뛰어난 성과를 내는 알고리즘
  - 앙상블 학습(ensemble learning)
  - 앙상블 학습은 대부분 결정 트리를 기반

- 비정형 데이터: 신경망 알고리즘에 사용(딥러닝)
  - 머신러닝 방법으로는 모델을 만들기 까다로움
  - 사진을 인식하고 텍스트를 이해하는 등이 가능

# 랜덤 포레스트 (Random Forest)
- 앙상블 학습의 대표 주자 중 하나
- 안정적인 성능 덕에 널리 사용 (가장 먼저 시도 권유)
- 선생님이 주로 사용하는 알고리즘 중 대표
- 결정 트리를 랜덤하게 만들어 결정 트리(나무)의 숲을 생성
- 각 결정 트리의 예측을 사용해 최족 예측 결정
- 각 노드 분할시 / 전체 특성 중 일부 특성을 무작위로 고른 다음 이 중에서 최선의 분할을 찾음
- 예를 들어 4개의 특성이 있따면 노드마다 2개를 랜덤하게 선택
- default 100개 트리 사용(보통 120~200)
- 각 트리의 클래스별 확률 평균해서 가장 높은 확률 클래스로 결정
- 랜덤하게 샘플과 특성을 사용 -> 과대적합 막아주고 + 검증/테스트 세트에서 안정적 성능
- 기본 매개변수 설정만으로도 어느 정도 좋은 결과!


# 부트스트랩 샘플(bootstrap sample)
- 부트스트랩 방식: 데이터 세트에서 중복을 허용하여 데이터를 샘플링하는 방식
- 각 트리를 훈련하기 위한 데이터를 랜덤하게 샘플 추출 -> 중복 가능!
  - 예) 1000개의 가방에서 1000개씩 샘플을 뽑을 때, 1개 뽑고, 뽑았던 1개를 다시 가방에 넣음 -> 중복된 샘플 뽑을 수 있음
- 이렇게 만든 샘플: 부트스트랩 샘플(bootstrap sample)
- 훈련 세트 크기와 같음: 1000개 가방에서 중복하여 1000개 샘플


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# 데이터 로드
import pandas as pd
wine = pd.read_csv('/content/drive/MyDrive/Data/wine.csv')
wine.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [4]:
# 훈련/테스트셋 분류
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()
train_input, test_input, train_target, test_target  = train_test_split(data, target, test_size=0.2, random_state=42)

In [5]:
# 교차 검증 수행 cross_validate()
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_jobs = -1, random_state = 42)

# return_train_score: 검증 점수 뿐만 아니라 훈련 세트 점수도 같이 반환
# scores = corss_valideate(rf, train_input, train_target, n_jobs = -1)
# print(np.mean(scores['test_score']))
# print(np.mean(scores['train_score'])) # 에러
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs = -1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9973541965122431 0.8905151032797809


# 특성 중요도
- 매개변수: 결정 트리의 앙상블이므로 모두 제공
  - `criterion, max_depth, max_features, mi_samples_split, min_impurity_decrease, min_samples,leaf` 등
- 중요도는 노드들의 지니불순도(Gini impurity)를 가지고 계산하는데 노드가 중요할 수록 불순도가 크게 감소한다는 사실을 이용한다.
- 노드는 한 특성의 값을 기준으로 분리가 되기 때문에 불순도를 크게 감소하는데 많이 사용된 특성이 중요도가 올라갈 것이다.
- 종속변수에 미치는 독립변수의 영향력을 알아보기 위해 feature importance를 확인해보는 방법도 있다.

In [6]:
# 그냥 Decision Tree: [0.12345626 0.86862934 0.0079144]
# 알코올 도수, 당도, pH값 순서
rf.fit(train_input, train_target)
print(rf.feature_importances_)
# 당도 중요도 감소
# 알코올 도수와 pH 특성 중요도 상승
# 랜덤 포레스트가 특성의 일부를 랜덤하게 선택
# 과대적합을 줄이고 일반화 성능을 높임!

[0.23167441 0.50039841 0.26792718]


# OOB(Out Of Bag) 샘플
- 중복 허용 -> 부트스트랩 샘플에 포함되지 않고 남는 샘플 -> 검증 세트 역할
- 부트스트랩 샘플로 훈련한 결정 트리 평가
- `oob_score` 매개변수를 True로 지정: 각 결정 트리의 OOB 점수를 평균하여 출력
- OOB 점수를 활용하면 교차 검증을 대신 -> 훈련 세트에 더 많은 샘플 사용


In [7]:
# n_estimators 매개변수로 트리개수 3000개로 지정 
rf = RandomForestClassifier(oob_score=True, n_jobs = -1, n_estimators=3000, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8966711564364056


# 엑스트라 트리(Extra Trees)
- 랜덤 포레스틔와 매우 비슷하게 동작
  - 기본적으로 100개의 결정 트리 훈련
  - 전체 특성 중 일부 특성을 랜덤하게 선택하여 노드를 분할하는 데 사용
- 가장 큰 차이점은 부트스트랩 샘플을 사용하지 않음!
- 노드를 분할할 때 가장 좋은 분할이 아니라 무작위로 분할
  - 성능이 낮아지지만 많은 트리를 앙상블
  - 과대적합을 막고 검증 세트 점수를 높일 수 있음
- 엑스트라 트리가 무작위성이 좀 더 크기 때문에
- 랜덤하게 노드를 분할하기 때문에 계산 속도가 빠름

In [10]:
from sklearn.ensemble import ExtraTreesClassifier

et = ExtraTreesClassifier(n_jobs = -1, random_state = 42)
scores = cross_validate(et, train_input, train_target, return_train_score = True, n_jobs = -1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974503966084433 0.8887848893166506


In [11]:
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


# 그레이디언트 부스팅(Gradient boosting)
- 깊이가 얕은 결정 트리를 사용하여 이전 트리의 오차를 보완하는 방식으로 앙상블
- 기본적으로 깊이가 3인 결정 트리를 100개 사용
- 깊이가 얕은 결정 트리를 사용: 과대적합에 강하고 높은 일반화 성능 기대
- 경사 하강법을 사용하여 트리를 앙상블에 추가
- 분류: 로지스틱 손실 함수 사용
- 회귀: 평균 제곱 오차 함수 사용


In [14]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state = 42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs = -1)
print(np.mean(scores['train_score']), np.mean(scores['test_score'])) 

0.8881086892152563 0.8720430147331015


In [15]:
# 특성 중요도 확인 결과, GB가 RF보다 당도에 더 집중
gb.fit(train_input, train_target)
print(gb.feature_importances_)
# 일반적으로 GB가 RF보다 조금 더 높은 성능을 얻을 수 있음
# 순서대로 트리를 추가하기 떄문에 훈련 속도가 느림
# n_jobs 매개변수가 없음


[0.11949946 0.74871836 0.13178218]


# 히스토그램 기반 그레이디언트 부스팅 (Histogram-based Gradient Boosting)
- 정형 데이터를 다루는 머신러닝 알고리즘 중 가장 인기가 높음
- 먼저 입력 특성을 256개의 구간으로 나눔
- 노드를 분할할 때 최적의 분할을 매우 빠르게 찾음
- 256개의 구간 중에서 하나를 떼어 놓고 누락된 값을 위해 사용 -> 입력에 누락된 특성이 있더라도 이를 전처리할 필요가 없음



- HistGradientBoostingClassifier 클래스 적용
- 기본 매개변수만 사용해도 안정적인 성능을 얻을 수 있음
- `max_iter` 매개변쉬: 트리 개수 지정(n_estimators 아님)

In [16]:
from sklearn.ensemble import HistGradientBoostingClassifier

hgb = HistGradientBoostingClassifier(random_state = 42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True, n_jobs = 1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9321723946453317 0.8801241948619236


In [17]:
hgb.fit(train_input, train_target)
hgb.score(test_input, test_target)

0.8723076923076923

# XGBoost
- 사이킷런 외에도 유명한 2가지 GB 라이브러리가 이미 코랩에 설치되어있음
- 뛰어난 예측 성능 / GBM 대비 빠른 수행 시간
- 과적합 규제 / 나무 가지치기
- 자체 내장된 교차 검증 / 결손값 자체 처리

In [18]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method = 'hist', random_state = 42)
scores = cross_validate(xgb, train_input, train_target, return_train_score = True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8824322471423747 0.8726214185237284


# LightGBM
- XGBoost와 함께 부스팅 계열 알고리즘에서 가장 각광받음
- XGBoost보다 학습에 걸리는 시간이 훨씬 적음
- 메모리 사용량도 상대적으로 적음(Light)
- 예측 성능은 별다른 차이 없음
- XGBoost보다 2년 후에 만들어짐: 장점은 계승 + 단점 보완

In [21]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state = 42)
scores = cross_validate(lgb, train_input, train_target, return_train_score = True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9338079582727165 0.8789710890649293
